name: Terraform CI Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
    parse-modules:
        outputs:
            modules: ${{ steps.get-modules.outputs.modules }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Get Terraform Modules folders
              id: get-modules
              run: |
                MODULES=$(ls -d modules/*/ | sed 's|modules/||g' | sed 's|/||g' | jq -R -s -c 'split("\n")[:-1]')
                echo "modules=$MODULES" >> $GITHUB_OUTPUT

            - name: Output Modules
              run: |
                echo "Modules: ${{ steps.get-modules.outputs.modules }}"

    module-checks:
        runs-on: ubuntu-latest
        needs: parse-modules
        strategy:
            matrix:
                module: ${{ fromJson(needs.parse-modules.outputs.modules) }}
        defaults:
          run:
            working-directory: 'modules/${{ matrix.module }}'
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: "1.14.6"

            - name: Terraform Format Check
              run: terraform fmt -check -recursive

            - name: Terraform Init
              run: terraform init -backend=false

            - name: Terraform Validate
              run: terraform validate -no-color

    
    parse-apps:
        outputs:
            apps: ${{ steps.get-apps.outputs.apps }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Get Terraform apps folders
              id: get-apps
              run: |
                APPS=$(ls -d apps/*/ | sed 's|apps/||g' | sed 's|/||g' | jq -R -s -c 'split("\n")[:-1]')
                echo "apps=$APPS" >> $GITHUB_OUTPUT

            - name: Output Apps
              run: |
                echo "Apps: ${{ steps.get-apps.outputs.apps }}"

    app-checks:
        runs-on: ubuntu-latest
        needs: parse-apps
        strategy:
            matrix:
                apps: ${{ fromJson(needs.parse-apps.outputs.apps) }}
        defaults:
          run:
            working-directory: 'apps/${{ matrix.apps }}'
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: "1.14.6"

            - name: Terraform Format Check
              run: terraform fmt -check -recursive
              
            - name: Terraform Init
              run: terraform init -backend=false

            - name: Terraform Validate
              run: terraform validate -no-color

    # previous-tag:
    #     runs-on: ubuntu-latest
    #     if: github.event_name == 'push'
    #     outputs:
    #         previous_tag: ${{ steps.get-previous-tag.outputs.previous_tag }}
    #     needs: [module-checks, app-checks]
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v6

    #         - name: Get previous tag
    #           id: get-previous-tag
    #           run: |
    #             git fetch --tags
    #             PREVIOUS_TAG=$(git describe --tags --abbrev=0)
    #             echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

    # create-tags:
    #     runs-on: ubuntu-latest
    #     if: github.event_name == 'push'
    #     outputs:
    #         new_tag: ${{ steps.create-tag.outputs.new_tag }}
    #     needs: [module-checks, app-checks]
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v6

    #         - name: Create tags for modules and apps
    #           id: create-tag
    #           run: |
    #             TAG="$(date +'%y.%m.%d')"

    #             git config --global user.name "github-actions"
    #             git config --global user.email "actions@github.com"

    #             git tag $TAG
    #             git push origin $TAG

    # generate-docs:
    #     runs-on: ubuntu-latest
    #     needs: [module-checks, app-checks, create-tags, previous-tag]
    #     outputs:
    #         change_log: ${{ steps.generate-docs.outputs.change_log }}
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v6

    #         - name: Generate documentation
    #           id: generate-docs
    #           run: |
    #             last_tag=${{ needs.previous-tag.outputs.previous_tag }}
    #             new_tag=${{ needs.create-tags.outputs.new_tag }}
    #             echo "Generating documentation for changes between $last_tag and $new_tag"

    #             echo "" >> CHANGELOG.md

    #             git log $last_tag..$new_tag --pretty=format:"- %s (%h)" >> CHANGELOG.md

    #             echo "Documentation generated and added to CHANGELOG.md"

    #             echo "change_log=$(cat CHANGELOG.md)" >> $GITHUB_OUTPUT

    # release:
    #     runs-on: ubuntu-latest
    #     needs: [generate-docs, create-tags]
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v6

    #         - name: Create GitHub Release
    #           uses: softprops/action-gh-release@v1
    #           with:
    #             tag_name: ${{ needs.create-tags.outputs.new_tag }}
    #             release_name: Release ${{ needs.create-tags.outputs.new_tag }}
    #             body: ${{ needs.generate-docs.outputs.change_log }}
    #           env:
    #             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
